
title: Muratcan Celayir
email: muratcancelayir@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My personal blog to keep things that I've learned in one place
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://muratcancelayir.github.io/"
twitter_username: m_celayir
github_username:  muratcancelayir

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

